export const BANGLA_SURAH_NAMES: { name: string; meaning: string }[] = [
  { name: 'আল-ফাতিহা', meaning: 'সূচনা' },
  { name: 'আল-বাক্বারাহ্', meaning: 'গাভী' },
  { name: 'আলে ইমরান', meaning: 'ইমরানের পরিবার' },
  { name: 'আন-নিসা', meaning: 'মহিলা' },
  { name: 'আল-মায়েদাহ্', meaning: 'খাদ্য পরিবেশিত টেবিল' },
  { name: 'আল-আন‘আম', meaning: 'গৃহপালিত পশু' },
  { name: 'আল-আ‘রাফ', meaning: 'উঁচু স্থানসমূহ' },
  { name: 'আল-আনফাল', meaning: 'যুদ্ধে-লব্ধ ধনসম্পদ' },
  { name: 'আত-তাওবাহ্', meaning: 'অনুশোচনা' },
  { name: 'ইউনুস', meaning: 'নবী ইউনুস' },
  { name: 'হূদ', meaning: 'নবী হূদ' },
  { name: 'ইউসুফ', meaning: 'নবী ইউসুফ' },
  { name: 'আর-রা‘দ', meaning: 'বজ্রনাদ' },
  { name: 'ইব্রাহীম', meaning: 'নবী ইব্রাহিম' },
  { name: 'আল-হিজর', meaning: 'পাথুরে পাহাড়' },
  { name: 'আন-নাহ্‌ল', meaning: 'মৌমাছি' },
  { name: 'আল-ইসরা', meaning: 'রাতের ভ্রমণ' },
  { name: 'আল-কাহফ', meaning: 'গুহা' },
  { name: 'মারইয়াম', meaning: 'মরিয়ম' },
  { name: 'ত্বা-হা', meaning: 'ত্বা-হা' },
  { name: 'আল-আম্বিয়া', meaning: 'নবিগণ' },
  { name: 'আল-হাজ্জ', meaning: 'হজ্জ' },
  { name: 'আল-মু’মিনূন', meaning: 'বিশ্বাসীগণ' },
  { name: 'আন-নূর', meaning: 'আলো' },
  { name: 'আল-ফুরক্বান', meaning: 'মানদণ্ড' },
  { name: 'আশ-শু‘আরা', meaning: 'কবিগণ' },
  { name: 'আন-নামল', meaning: 'পিঁপড়া' },
  { name: 'আল-ক্বাসাস', meaning: 'কাহিনি' },
  { name: 'আল-‘আনকাবূত', meaning: 'মাকড়শা' },
  { name: 'আর-রূম', meaning: 'রোম' },
  { name: 'লুক্বমান', meaning: 'লোকমান' },
  { name: 'আস-সাজদা', meaning: 'সিজদা' },
  { name: 'আল-আহযাব', meaning: 'একত্রিত বাহিনী' },
  { name: 'সাবা', meaning: 'সাবা' },
  { name: 'ফাতের', meaning: 'সৃষ্টিকর্তা' },
  { name: 'ইয়াসীন', meaning: 'ইয়াসিন' },
  { name: 'আস-সাফ্‌ফাত', meaning: 'সারিবদ্ধ' },
  { name: 'সাদ', meaning: 'সাদ' },
  { name: 'আয-যুমার', meaning: 'দলসমূহ' },
  { name: 'গাফের', meaning: 'ক্ষমাকারী' },
  { name: 'ফুসসিলাত', meaning: 'বিশদ বিবৃত' },
  { name: 'আশ-শূরা', meaning: 'পরামর্শ' },
  { name: 'আয-যুখরুফ', meaning: 'সোনার অলংকার' },
  { name: 'আদ-দুখান', meaning: 'ধোঁয়া' },
  { name: 'আল-জাসিয়া', meaning: 'নতজানু' },
  { name: 'আল-আহক্বাফ', meaning: 'বালুর পাহাড়' },
  { name: 'মুহাম্মাদ', meaning: 'মুহাম্মদ' },
  { name: 'আল-ফাতহ', meaning: 'বিজয়' },
  { name: 'আল-হুজুরাত', meaning: 'অন্তঃকক্ষসমূহ' },
  { name: 'ক্বাফ', meaning: 'ক্বাফ' },
  { name: 'আয-যারিয়াত', meaning: 'বিক্ষিপ্তকারী' },
  { name: 'আত-তূর', meaning: 'তূর পর্বত' },
  { name: 'আন-নাজম', meaning: 'নক্ষত্র' },
  { name: 'আল-ক্বামার', meaning: 'চাঁদ' },
  { name: 'আর-রাহমান', meaning: 'দয়াময়' },
  { name: 'আল-ওয়াক্বি‘আহ', meaning: 'মহাসংঘটন' },
  { name: 'আল-হাদীদ', meaning: 'লোহা' },
  { name: 'আল-মুজাদালাহ্', meaning: 'অনুযোগকারিণী' },
  { name: 'আল-হাশর', meaning: 'সমাবেশ' },
  { name: 'আল-মুমতাহিনা', meaning: 'পরীক্ষিত নারী' },
  { name: 'আস-সাফ', meaning: 'সারবদ্ধ' },
  { name: 'আল-জুমু‘আ', meaning: 'জুমু‘আ' },
  { name: 'আল-মুনাফিক্বূন', meaning: 'মুনাফিকগণ' },
  { name: 'আত-তাগাবুন', meaning: 'পারস্পরিক মোহর' },
  { name: 'আত-ত্বালাক', meaning: 'তালাক' },
  { name: 'আত-তাহরীম', meaning: 'নিষিদ্ধকরণ' },
  { name: 'আল-মুলক', meaning: 'রাজত্ব' },
  { name: 'আল-ক্বালাম', meaning: 'কলম' },
  { name: 'আল-হাক্কাহ্', meaning: 'নিশ্চিত ঘটনা' },
  { name: 'আল-মা‘আরেজ', meaning: 'ঊর্ধ্বগামী সোপান' },
  { name: 'নূহ', meaning: 'নূহ' },
  { name: 'আল-জিন্ন', meaning: 'জিন' },
  { name: 'আল-মুযযাম্মিল', meaning: 'চাদর আবৃত' },
  { name: 'আল-মুদ্দাস্‌সির', meaning: 'বস্ত্রাবৃত' },
  { name: 'আল-ক্বিয়ামাহ্‌', meaning: 'কিয়ামত' },
  { name: 'আল-ইনসান', meaning: 'মানুষ' },
  { name: 'আল-মুরসালাত', meaning: 'প্রেরিতগণ' },
  { name: 'আন-নাবা', meaning: 'সংবাদ' },
  { name: 'আন-নাযি‘আত', meaning: 'প্রত্যাহারকারী' },
  { name: '‘আবাসা', meaning: 'ভ্রুকুটি' },
  { name: 'আত-তাকভীর', meaning: 'অন্ধকারাচ্ছন্ন' },
  { name: 'আল-ইনফিতার', meaning: 'বিদীর্ণ হওয়া' },
  { name: 'আল-মুতাফফিফীন', meaning: 'প্রতারণাকারী' },
  { name: 'আল-ইনশিক্বাক', meaning: 'বিদীর্ণ' },
  { name: 'আল-বুরূজ', meaning: 'নক্ষত্রপুঞ্জ' },
  { name: 'আত-ত্বারেক', meaning: 'রাতের আগন্তুক' },
  { name: 'আল-আ‘লা', meaning: 'সর্বোত্তম' },
  { name: 'আল-গাশিয়াহ্', meaning: 'আবরণকারী' },
  { name: 'আল-ফাজর', meaning: 'ভোর' },
  { name: 'আল-বালাদ', meaning: 'নগরী' },
  { name: 'আশ-শামস', meaning: 'সূর্য' },
  { name: 'আল-লাইল', meaning: 'রাত' },
  { name: 'আদ্ব-দ্বুহা', meaning: 'পূর্বাহ্ন' },
  { name: 'আশ-শারহ', meaning: 'প্রশস্তকরণ' },
  { name: 'আত-তীন', meaning: 'ডুমুর' },
  { name: 'আল-‘আলাক্ব', meaning: 'রক্তপিন্ড' },
  { name: 'আল-ক্বাদর', meaning: 'কদর' },
  { name: 'আল-বায়্যিনাহ্', meaning: 'সুস্পষ্ট প্রমাণ' },
  { name: 'আয-যালযালাহ্', meaning: 'ভূমিকম্প' },
  { name: 'আল-‘আদিয়াত', meaning: 'অভিযানকারী' },
  { name: 'আল-ক্বারি‘আহ্', meaning: 'মহাসংকট' },
  { name: 'আত-তাকাসুর', meaning: 'প্রাচুর্যের প্রতিযোগিতা' },
  { name: 'আল-‘আসর', meaning: 'সময়' },
  { name: 'আল-হুমাযাহ্', meaning: 'পরনিন্দাকারী' },
  { name: 'আল-ফীল', meaning: 'হাতি' },
  { name: 'ক্বুরাইশ', meaning: 'কুরাইশ' },
  { name: 'আল-মা‘ঊন', meaning: 'সাহায্য সামগ্রী' },
  { name: 'আল-কাউসার', meaning: 'প্রাচুর্য' },
  { name: 'আল-কাফিরূন', meaning: 'কাফিরগণ' },
  { name: 'আন-নাসর', meaning: 'সাহায্য' },
  { name: 'আল-মাসাদ', meaning: 'পাকানো রশি' },
  { name: 'আল-ইখলাস', meaning: 'একনিষ্ঠতা' },
  { name: 'আল-ফালাক্ব', meaning: 'ভোর' },
  { name: 'আন-নাস', meaning: 'মানবজাতি' },
];

export const getBanglaSurahName = (number: number) =>
  BANGLA_SURAH_NAMES[number - 1]?.name || 'সূরা';